export const WEAPON = [
    { name: 'わかばシューター', lc: 'SHOOTER', sc: 'わかばシューター', role: 'PAINT', range: 'SHORT' },
    { name: 'もみじシューター', lc: 'SHOOTER', sc: 'わかばシューター', role: 'PAINT', range: 'SHORT' },
    { name: 'ボールドマーカー', lc: 'SHOOTER', sc: 'ボールドマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'ボールドマーカーネオ', lc: 'SHOOTER', sc: 'ボールドマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'シャープマーカー', lc: 'SHOOTER', sc: 'シャープマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'シャープマーカーネオ', lc: 'SHOOTER', sc: 'シャープマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'シャープマーカーGECK', lc: 'SHOOTER', sc: 'シャープマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'プロモデラーMG', lc: 'SHOOTER', sc: 'プロモデラー', role: 'PAINT', range: 'SHORT' },
    { name: 'プロモデラーRG', lc: 'SHOOTER', sc: 'プロモデラー', role: 'PAINT', range: 'SHORT' },
    { name: 'プロモデラー彩', lc: 'SHOOTER', sc: 'プロモデラー', role: 'PAINT', range: 'SHORT' },
    { name: 'N-ZAP85', lc: 'SHOOTER', sc: 'N-ZAP', role: 'PAINT', range: 'SHORT' },
    { name: 'N-ZAP89', lc: 'SHOOTER', sc: 'N-ZAP', role: 'PAINT', range: 'SHORT' },
    { name: 'スプラシューター', lc: 'SHOOTER', sc: 'スプラシューター', role: 'BALANCED', range: 'SHORT' },
    { name: 'スプラシューターコラボ', lc: 'SHOOTER', sc: 'スプラシューター', role: 'BALANCED', range: 'SHORT' },
    { name: 'スプラシューター煌', lc: 'SHOOTER', sc: 'スプラシューター', role: 'BALANCED', range: 'SHORT' },
    { name: '.52ガロン', lc: 'SHOOTER', sc: '.52ガロン', role: 'BALANCED', range: 'SHORT' },
    { name: '.52ガロンデコ', lc: 'SHOOTER', sc: '.52ガロン', role: 'BALANCED', range: 'SHORT' },
    { name: 'プライムシューター', lc: 'SHOOTER', sc: 'プライムシューター', role: 'KILL', range: 'MID' },
    { name: 'プライムシューターコラボ', lc: 'SHOOTER', sc: 'プライムシューター', role: 'KILL', range: 'MID' },
    { name: 'プライムシューターFRZN', lc: 'SHOOTER', sc: 'プライムシューター', role: 'KILL', range: 'MID' },
    { name: '.96ガロン', lc: 'SHOOTER', sc: '.96ガロン', role: 'BALANCED', range: 'MID' },
    { name: '.96ガロンデコ', lc: 'SHOOTER', sc: '.96ガロン', role: 'BALANCED', range: 'MID' },
    { name: '.96ガロン爪', lc: 'SHOOTER', sc: '.96ガロン', role: 'BALANCED', range: 'MID' },
    { name: 'スペースシューター', lc: 'SHOOTER', sc: 'スペースシューター', role: 'PAINT', range: 'MID' },
    { name: 'スペースシューターコラボ', lc: 'SHOOTER', sc: 'スペースシューター', role: 'PAINT', range: 'MID' },
    { name: 'L3リールガン', lc: 'SHOOTER', sc: 'L3リールガン', role: 'BALANCED', range: 'SHORT' },
    { name: 'L3リールガンD', lc: 'SHOOTER', sc: 'L3リールガン', role: 'BALANCED', range: 'SHORT' },
    { name: 'L3リールガン箔', lc: 'SHOOTER', sc: 'L3リールガン', role: 'BALANCED', range: 'SHORT' },
    { name: 'H3リールガン', lc: 'SHOOTER', sc: 'H3リールガン', role: 'BALANCED', range: 'MID' },
    { name: 'H3リールガンD', lc: 'SHOOTER', sc: 'H3リールガン', role: 'BALANCED', range: 'MID' },
    { name: 'H3リールガンSNAK', lc: 'SHOOTER', sc: 'H3リールガン', role: 'PAINT', range: 'MID' },
    { name: 'ボトルガイザー', lc: 'SHOOTER', sc: 'ボトルガイザー', role: 'KILL', range: 'LONG' },
    { name: 'ボトルガイザーフォイル', lc: 'SHOOTER', sc: 'ボトルガイザー', role: 'KILL', range: 'LONG' },
    { name: 'ジェットスイーパー', lc: 'SHOOTER', sc: 'ジェットスイーパー', role: 'BALANCED', range: 'LONG' },
    { name: 'ジェットスイーパーカスタム', lc: 'SHOOTER', sc: 'ジェットスイーパー', role: 'BALANCED', range: 'LONG' },
    { name: 'ジェットスイーパーCOBR', lc: 'SHOOTER', sc: 'ジェットスイーパー', role: 'BALANCED', range: 'LONG' },
    { name: 'カーボンローラー', lc: 'ROLLER', sc: 'カーボンローラー', role: 'KILL', range: 'SHORT' },
    { name: 'カーボンローラーデコ', lc: 'ROLLER', sc: 'カーボンローラー', role: 'KILL', range: 'SHORT' },
    { name: 'カーボンローラーANGL', lc: 'ROLLER', sc: 'カーボンローラー', role: 'KILL', range: 'SHORT' },
    { name: 'スプラローラー', lc: 'ROLLER', sc: 'スプラローラー', role: 'KILL', range: 'SHORT' },
    { name: 'スプラローラーコラボ', lc: 'ROLLER', sc: 'スプラローラー', role: 'KILL', range: 'SHORT' },
    { name: 'ダイナモローラー', lc: 'ROLLER', sc: 'ダイナモローラー', role: 'KILL', range: 'MID' },
    { name: 'ダイナモローラーテスラ', lc: 'ROLLER', sc: 'ダイナモローラー', role: 'KILL', range: 'MID' },
    { name: 'ダイナモローラー冥', lc: 'ROLLER', sc: 'ダイナモローラー', role: 'KILL', range: 'MID' },
    { name: 'ヴァリアブルローラー', lc: 'ROLLER', sc: 'ヴァリアブルローラー', role: 'PAINT', range: 'MID' },
    { name: 'ヴァリアブルローラーフォイル', lc: 'ROLLER', sc: 'ヴァリアブルローラー', role: 'PAINT', range: 'MID' },
    { name: 'ワイドローラー', lc: 'ROLLER', sc: 'ワイドローラー', role: 'PAINT', range: 'SHORT' },
    { name: 'ワイドローラーコラボ', lc: 'ROLLER', sc: 'ワイドローラー', role: 'PAINT', range: 'SHORT' },
    { name: 'ワイドローラー惑', lc: 'ROLLER', sc: 'ワイドローラー', role: 'PAINT', range: 'SHORT' },
    { name: 'ノヴァブラスター', lc: 'BLUSTER', sc: 'ノヴァブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ノヴァブラスターネオ', lc: 'BLUSTER', sc: 'ノヴァブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ホットブラスター', lc: 'BLUSTER', sc: 'ホットブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ホットブラスターカスタム', lc: 'BLUSTER', sc: 'ホットブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ホットブラスター艶', lc: 'BLUSTER', sc: 'ホットブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ロングブラスター', lc: 'BLUSTER', sc: 'ロングブラスター', role: 'KILL', range: 'MID' },
    { name: 'ロングブラスターカスタム', lc: 'BLUSTER', sc: 'ロングブラスター', role: 'KILL', range: 'MID' },
    { name: 'クラッシュブラスター', lc: 'BLUSTER', sc: 'クラッシュブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'クラッシュブラスターネオ', lc: 'BLUSTER', sc: 'クラッシュブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ラピッドブラスター', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'MID' },
    { name: 'ラピッドブラスターデコ', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'MID' },
    { name: 'ラピッドブラスターエリート', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'LONG' },
    { name: 'ラピッドブラスターエリートデコ', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'LONG' },
    { name: 'ラピッドブラスターエリートWNTR', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'LONG' },
    { name: 'S-BLAST92', lc: 'BLUSTER', sc: 'S-BLAST', role: 'KILL', range: 'MID' },
    { name: 'S-BLAST91', lc: 'BLUSTER', sc: 'S-BLAST', role: 'KILL', range: 'MID' },
    { name: 'バケットスロッシャー', lc: 'SLOSHER', sc: 'バケットスロッシャー', role: 'KILL', range: 'MID' },
    { name: 'バケットスロッシャーデコ', lc: 'SLOSHER', sc: 'バケットスロッシャー', role: 'KILL', range: 'MID' },
    { name: 'ヒッセン', lc: 'SLOSHER', sc: 'ヒッセン', role: 'KILL', range: 'SHORT' },
    { name: 'ヒッセンヒュー', lc: 'SLOSHER', sc: 'ヒッセン', role: 'BALANCED', range: 'SHORT' },
    { name: 'ヒッセンASH', lc: 'SLOSHER', sc: 'ヒッセン', role: 'KILL', range: 'SHORT' },
    { name: 'スクリュースロッシャー', lc: 'SLOSHER', sc: 'スクリュースロッシャー', role: 'KILL', range: 'MID' },
    { name: 'スクリュースロッシャーネオ', lc: 'SLOSHER', sc: 'スクリュースロッシャー', role: 'KILL', range: 'MID' },
    { name: 'オーバーフロッシャー', lc: 'SLOSHER', sc: 'オーバーフロッシャー', role: 'BALANCED', range: 'MID' },
    { name: 'オーバーフロッシャーデコ', lc: 'SLOSHER', sc: 'オーバーフロッシャー', role: 'BALANCED', range: 'MID' },
    { name: 'モップリン', lc: 'SLOSHER', sc: 'モップリン', role: 'BALANCED', range: 'MID' },
    { name: 'モップリンD', lc: 'SLOSHER', sc: 'モップリン', role: 'BALANCED', range: 'MID' },
    { name: 'モップリン角', lc: 'SLOSHER', sc: 'モップリン', role: 'BALANCED', range: 'MID' },
    { name: 'エクスプロッシャー', lc: 'SLOSHER', sc: 'エクスプロッシャー', role: 'BALANCED', range: 'LONG' },
    { name: 'エクスプロッシャーカスタム', lc: 'SLOSHER', sc: 'エクスプロッシャー', role: 'BALANCED', range: 'LONG' },
    { name: 'スプラスピナー', lc: 'SPINNER', sc: 'スプラスピナー', role: 'PAINT', range: 'MID' },
    { name: 'スプラスピナーコラボ', lc: 'SPINNER', sc: 'スプラスピナー', role: 'PAINT', range: 'MID' },
    { name: 'スプラスピナーPYTN', lc: 'SPINNER', sc: 'スプラスピナー', role: 'PAINT', range: 'MID' },
    { name: 'ノーチラス47', lc: 'SPINNER', sc: 'ノーチラス', role: 'KILL', range: 'MID' },
    { name: 'ノーチラス79', lc: 'SPINNER', sc: 'ノーチラス', role: 'KILL', range: 'MID' },
    { name: 'イグザミナー', lc: 'SPINNER', sc: 'イグザミナー', role: 'BALANCED', range: 'MID' },
    { name: 'イグザミナーヒュー', lc: 'SPINNER', sc: 'イグザミナー', role: 'BALANCED', range: 'MID' },
    { name: 'バレルスピナー', lc: 'SPINNER', sc: 'バレルスピナー', role: 'BALANCED', range: 'LONG' },
    { name: 'バレルスピナーデコ', lc: 'SPINNER', sc: 'バレルスピナー', role: 'BALANCED', range: 'LONG' },
    { name: 'クーゲルシュライバー', lc: 'SPINNER', sc: 'クーゲルシュライバー', role: 'BALANCED', range: 'LONG' },
    { name: 'クーゲルシュライバーヒュー', lc: 'SPINNER', sc: 'クーゲルシュライバー', role: 'BALANCED', range: 'LONG' },
    { name: 'ハイドラント', lc: 'SPINNER', sc: 'ハイドラント', role: 'KILL', range: 'LONG' },
    { name: 'ハイドラントカスタム', lc: 'SPINNER', sc: 'ハイドラント', role: 'KILL', range: 'LONG' },
    { name: 'ハイドラント圧', lc: 'SPINNER', sc: 'ハイドラント', role: 'KILL', range: 'LONG' },
    { name: 'スプラマニューバー', lc: 'DUALIES', sc: 'スプラマニューバー', role: 'BALANCED', range: 'SHORT' },
    { name: 'スプラマニューバーコラボ', lc: 'DUALIES', sc: 'スプラマニューバー', role: 'KILL', range: 'SHORT' },
    { name: 'スプラマニューバー耀', lc: 'DUALIES', sc: 'スプラマニューバー', role: 'BALANCED', range: 'SHORT' },
    { name: 'スパッタリー', lc: 'DUALIES', sc: 'スパッタリー', role: 'BALANCED', range: 'SHORT' },
    { name: 'スパッタリーヒュー', lc: 'DUALIES', sc: 'スパッタリー', role: 'BALANCED', range: 'SHORT' },
    { name: 'スパッタリーOWL', lc: 'DUALIES', sc: 'スパッタリー', role: 'BALANCED', range: 'SHORT' },
    { name: 'ケルビン525', lc: 'DUALIES', sc: 'ケルビン', role: 'KILL', range: 'MID' },
    { name: 'ケルビン525デコ', lc: 'DUALIES', sc: 'ケルビン', role: 'KILL', range: 'MID' },
    { name: 'デュアルスイーパー', lc: 'DUALIES', sc: 'デュアルスイーパー', role: 'BALANCED', range: 'MID' },
    { name: 'デュアルスイーパーカスタム', lc: 'DUALIES', sc: 'デュアルスイーパー', role: 'BALANCED', range: 'MID' },
    { name: 'デュアルスイーパー蹄', lc: 'DUALIES', sc: 'デュアルスイーパー', role: 'BALANCED', range: 'MID' },
    { name: 'クアッドホッパーブラック', lc: 'DUALIES', sc: 'クアッドホッパー', role: 'KILL', range: 'MID' },
    { name: 'クアッドホッパーホワイト', lc: 'DUALIES', sc: 'クアッドホッパー', role: 'KILL', range: 'MID' },
    { name: 'ガエンFF', lc: 'DUALIES', sc: 'ガエンFF', role: 'BALANCED', range: 'LONG' },
    { name: 'ガエンFFカスタム', lc: 'DUALIES', sc: 'ガエンFF', role: 'BALANCED', range: 'LONG' },
    { name: 'パラシェルター', lc: 'SHELTER', sc: 'パラシェルター', role: 'TANK', range: 'SHORT' },
    { name: 'パラシェルターソレーラ', lc: 'SHELTER', sc: 'パラシェルター', role: 'TANK', range: 'SHORT' },
    { name: 'キャンピングシェルター', lc: 'SHELTER', sc: 'キャンピングシェルター', role: 'TANK', range: 'MID' },
    { name: 'キャンピングシェルターソレーラ', lc: 'SHELTER', sc: 'キャンピングシェルター', role: 'TANK', range: 'MID' },
    { name: 'キャンピングシェルターCREM', lc: 'SHELTER', sc: 'キャンピングシェルター', role: 'TANK', range: 'MID' },
    { name: 'スパイガジェット', lc: 'SHELTER', sc: 'スパイガジェット', role: 'TANK', range: 'SHORT' },
    { name: 'スパイガジェットソレーラ', lc: 'SHELTER', sc: 'スパイガジェット', role: 'TANK', range: 'SHORT' },
    { name: 'スパイガジェット繚', lc: 'SHELTER', sc: 'スパイガジェット', role: 'TANK', range: 'SHORT' },
    { name: '24式張替傘・甲', lc: 'SHELTER', sc: '24式張替傘', role: 'TANK', range: 'SHORT' },
    { name: '24式張替傘・乙', lc: 'SHELTER', sc: '24式張替傘', role: 'TANK', range: 'SHORT' },
    { name: 'パブロ', lc: 'BRUSH', sc: 'パブロ', role: 'TANK', range: 'SHORT' },
    { name: 'パブロヒュー', lc: 'BRUSH', sc: 'パブロ', role: 'TANK', range: 'SHORT' },
    { name: 'ホクサイ', lc: 'BRUSH', sc: 'ホクサイ', role: 'KILL', range: 'SHORT' },
    { name: 'ホクサイヒュー', lc: 'BRUSH', sc: 'ホクサイ', role: 'KILL', range: 'SHORT' },
    { name: 'ホクサイ彗', lc: 'BRUSH', sc: 'ホクサイ', role: 'KILL', range: 'SHORT' },
    { name: 'フィンセント', lc: 'BRUSH', sc: 'フィンセント', role: 'KILL', range: 'SHORT' },
    { name: 'フィンセントヒュー', lc: 'BRUSH', sc: 'フィンセント', role: 'KILL', range: 'SHORT' },
    { name: 'フィンセントBRNZ', lc: 'BRUSH', sc: 'フィンセント', role: 'KILL', range: 'SHORT' },
    { name: 'ドライブワイパー', lc: 'WIPER', sc: 'ドライブワイパー', role: 'BALANCED', range: 'SHORT' },
    { name: 'ドライブワイパーデコ', lc: 'WIPER', sc: 'ドライブワイパー', role: 'BALANCED', range: 'SHORT' },
    { name: 'ドライブワイパーRUST', lc: 'WIPER', sc: 'ドライブワイパー', role: 'BALANCED', range: 'SHORT' },
    { name: 'ジムワイパー', lc: 'WIPER', sc: 'ジムワイパー', role: 'KILL', range: 'MID' },
    { name: 'ジムワイパーヒュー', lc: 'WIPER', sc: 'ジムワイパー', role: 'BALANCED', range: 'MID' },
    { name: 'ジムワイパー封', lc: 'WIPER', sc: 'ジムワイパー', role: 'BALANCED', range: 'MID' },
    { name: 'デンタルワイパーミント', lc: 'WIPER', sc: 'デンタルワイパー', role: 'BALANCED', range: 'MID' },
    { name: 'デンタルワイパースミ', lc: 'WIPER', sc: 'デンタルワイパー', role: 'BALANCED', range: 'MID' },
    { name: 'トライストリンガー', lc: 'STRINGER', sc: 'トライストリンガー', role: 'KILL', range: 'LONG'},
    { name: 'トライストリンガーコラボ', lc: 'STRINGER', sc: 'トライストリンガー', role: 'KILL', range: 'LONG'},
    { name: 'トライストリンガー燈', lc: 'STRINGER', sc: 'トライストリンガー', role: 'KILL', range: 'LONG'},
    { name: 'フルイドV', lc: 'STRINGER', sc: 'フルイドV', role: 'BALANCED', range: 'LONG'},
    { name: 'フルイドVカスタム', lc: 'STRINGER', sc: 'フルイドV', role: 'BALANCED', range: 'LONG'},
    { name: 'LACT-450', lc: 'STRINGER', sc: 'LACT-450', role: 'PAINT', range: 'MID'},
    { name: 'LACT-450デコ', lc: 'STRINGER', sc: 'LACT-450', role: 'PAINT', range: 'MID'},
    { name: 'LACT-450MILK', lc: 'STRINGER', sc: 'LACT-450', role: 'PAINT', range: 'MID'},
    { name: 'スクイックリンα', lc: 'CHARGER', sc: 'スクイックリン', role: 'KILL', range: 'MID'},
    { name: 'スクイックリンβ', lc: 'CHARGER', sc: 'スクイックリン', role: 'KILL', range: 'MID'},
    { name: 'ソイチューバー', lc: 'CHARGER', sc: 'ソイチューバー', role: 'BALANCED', range: 'MID'},
    { name: 'ソイチューバーカスタム', lc: 'CHARGER', sc: 'ソイチューバー', role: 'BALANCED', range: 'MID'},
    { name: '14式竹筒銃・甲', lc: 'CHARGER', sc: '14式竹筒銃', role: 'KILL', range: 'MID'},
    { name: '14式竹筒銃・乙', lc: 'CHARGER', sc: '14式竹筒銃', role: 'KILL', range: 'MID'},
    { name: 'R-PEN/5H', lc: 'CHARGER', sc: 'R-PEN', role: 'PAINT', range: 'LONG'},
    { name: 'R-PEN/5B', lc: 'CHARGER', sc: 'R-PEN', role: 'PAINT', range: 'LONG'},
    { name: 'スプラチャージャー', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'スプラチャージャーコラボ', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'スプラチャージャースコープ', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'スプラチャージャースコープコラボ', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'スプラチャージャーFRST', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'BALANCED', range: 'LONG'},
    { name: 'スプラスコープFRST', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'BALANCED', range: 'LONG'},
    { name: 'リッター4K', lc: 'CHARGER', sc: 'リッター4K', role: 'KILL', range: 'LONG'},
    { name: 'リッター4Kカスタム', lc: 'CHARGER', sc: 'リッター4K', role: 'KILL', range: 'LONG'},
    { name: 'リッター4Kスコープ', lc: 'CHARGER', sc: 'リッター4K', role: 'KILL', range: 'LONG'},
    { name: 'リッター4Kスコープカスタム', lc: 'CHARGER', sc: 'リッター4K', role: 'KILL', range: 'LONG'},
    { name: '自由', lc: 'FREE', sc: '自由', role: 'FREE', range: 'FREE'},
] as const;

export type Weapon = typeof WEAPON[number];
export type WeaponName = Weapon['name'];
export type WeaponRole = Weapon['role'];
export type WeaponLc = Weapon['lc'];
export type WeaponSc = Weapon['sc'];
export type WeaponRange = Weapon['range'];