import type { Weapon } from '@common/types';

export const WEAPON: readonly Weapon[] = [
    { name: 'わかばシューター', lc: 'SHOOTER', sc: 'わかばシューター', role: 'PAINT', range: 'SHORT' },
    { name: 'もみじシューター', lc: 'SHOOTER', sc: 'わかばシューター', role: 'PAINT', range: 'SHORT' },
    { name: 'おちばシューター', lc: 'SHOOTER', sc: 'わかばシューター', role: 'PAINT', range: 'SHORT' },
    { name: 'ボールドマーカー', lc: 'SHOOTER', sc: 'ボールドマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'ボールドマーカーネオ', lc: 'SHOOTER', sc: 'ボールドマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'ボールドマーカー7', lc: 'SHOOTER', sc: 'ボールドマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'シャープマーカー', lc: 'SHOOTER', sc: 'シャープマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'シャープマーカーネオ', lc: 'SHOOTER', sc: 'シャープマーカー', role: 'PAINT', range: 'SHORT' },
    { name: 'プロモデラーMG', lc: 'SHOOTER', sc: 'プロモデラー', role: 'PAINT', range: 'SHORT' },
    { name: 'プロモデラーRG', lc: 'SHOOTER', sc: 'プロモデラー', role: 'PAINT', range: 'SHORT' },
    { name: 'プロモデラーPG', lc: 'SHOOTER', sc: 'プロモデラー', role: 'PAINT', range: 'SHORT' },
    { name: 'N-ZAP85', lc: 'SHOOTER', sc: 'N-ZAP', role: 'PAINT', range: 'SHORT' },
    { name: 'N-ZAP89', lc: 'SHOOTER', sc: 'N-ZAP', role: 'PAINT', range: 'SHORT' },
    { name: 'N-ZAP83', lc: 'SHOOTER', sc: 'N-ZAP', role: 'PAINT', range: 'SHORT' },
    { name: 'スプラシューター', lc: 'SHOOTER', sc: 'スプラシューター', role: 'BALANCED', range: 'SHORT' },
    { name: 'スプラシューターコラボ', lc: 'SHOOTER', sc: 'スプラシューター', role: 'BALANCED', range: 'SHORT' },
    { name: 'スプラシューターベッチュー', lc: 'SHOOTER', sc: 'スプラシューター', role: 'PAINT', range: 'SHORT' },
    { name: '.52ガロン', lc: 'SHOOTER', sc: '.52ガロン', role: 'BALANCED', range: 'SHORT' },
    { name: '.52ガロンデコ', lc: 'SHOOTER', sc: '.52ガロン', role: 'BALANCED', range: 'SHORT' },
    { name: '.52ガロンベッチュー', lc: 'SHOOTER', sc: '.52ガロン', role: 'BALANCED', range: 'SHORT' },
    { name: 'プライムシューター', lc: 'SHOOTER', sc: 'プライムシューター', role: 'KILL', range: 'MID' },
    { name: 'プライムシューターコラボ', lc: 'SHOOTER', sc: 'プライムシューター', role: 'KILL', range: 'MID' },
    { name: 'プライムシューターベッチュー', lc: 'SHOOTER', sc: 'プライムシューター', role: 'KILL', range: 'MID' },
    { name: '.96ガロン', lc: 'SHOOTER', sc: '.96ガロン', role: 'BALANCED', range: 'MID' },
    { name: '.96ガロンデコ', lc: 'SHOOTER', sc: '.96ガロン', role: 'BALANCED', range: 'MID' },
    { name: 'L3リールガン', lc: 'SHOOTER', sc: 'L3リールガン', role: 'BALANCED', range: 'SHORT' },
    { name: 'L3リールガンD', lc: 'SHOOTER', sc: 'L3リールガン', role: 'BALANCED', range: 'SHORT' },
    { name: 'L3リールガンベッチュー', lc: 'SHOOTER', sc: 'L3リールガン', role: 'BALANCED', range: 'SHORT' },
    { name: 'H3リールガン', lc: 'SHOOTER', sc: 'H3リールガン', role: 'BALANCED', range: 'MID' },
    { name: 'H3リールガンD', lc: 'SHOOTER', sc: 'H3リールガン', role: 'PAINT', range: 'MID' },
    { name: 'H3リールガンチェリー', lc: 'SHOOTER', sc: 'H3リールガン', role: 'BALANCED', range: 'MID' },
    { name: 'ボトルガイザー', lc: 'SHOOTER', sc: 'ボトルガイザー', role: 'KILL', range: 'LONG' },
    { name: 'ボトルガイザーフォイル', lc: 'SHOOTER', sc: 'ボトルガイザー', role: 'KILL', range: 'LONG' },
    { name: 'ジェットスイーパー', lc: 'SHOOTER', sc: 'ジェットスイーパー', role: 'BALANCED', range: 'LONG' },
    { name: 'ジェットスイーパーカスタム', lc: 'SHOOTER', sc: 'ジェットスイーパー', role: 'BALANCED', range: 'LONG' },
    { name: 'カーボンローラー', lc: 'ROLLER', sc: 'カーボンローラー', role: 'KILL', range: 'SHORT' },
    { name: 'カーボンローラーデコ', lc: 'ROLLER', sc: 'カーボンローラー', role: 'KILL', range: 'SHORT' },
    { name: 'スプラローラー', lc: 'ROLLER', sc: 'スプラローラー', role: 'KILL', range: 'SHORT' },
    { name: 'スプラローラーコラボ', lc: 'ROLLER', sc: 'スプラローラー', role: 'KILL', range: 'SHORT' },
    { name: 'スプラローラーベッチュー', lc: 'ROLLER', sc: 'スプラローラー', role: 'KILL', range: 'SHORT' },
    { name: 'ダイナモローラー', lc: 'ROLLER', sc: 'ダイナモローラー', role: 'KILL', range: 'MID' },
    { name: 'ダイナモローラーテスラ', lc: 'ROLLER', sc: 'ダイナモローラー', role: 'KILL', range: 'MID' },
    { name: 'ダイナモローラーベッチュー', lc: 'ROLLER', sc: 'ダイナモローラー', role: 'KILL', range: 'MID' },
    { name: 'ヴァリアブルローラー', lc: 'ROLLER', sc: 'ヴァリアブルローラー', role: 'BALANCED', range: 'MID' },
    { name: 'ヴァリアブルローラーフォイル', lc: 'ROLLER', sc: 'ヴァリアブルローラー', role: 'PAINT', range: 'MID' },
    { name: 'ノヴァブラスター', lc: 'BLUSTER', sc: 'ノヴァブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ノヴァブラスターネオ', lc: 'BLUSTER', sc: 'ノヴァブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ノヴァブラスターベッチュー', lc: 'BLUSTER', sc: 'ノヴァブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ホットブラスター', lc: 'BLUSTER', sc: 'ホットブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ホットブラスターカスタム', lc: 'BLUSTER', sc: 'ホットブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ロングブラスター', lc: 'BLUSTER', sc: 'ロングブラスター', role: 'KILL', range: 'MID' },
    { name: 'ロングブラスターカスタム', lc: 'BLUSTER', sc: 'ロングブラスター', role: 'KILL', range: 'MID' },
    { name: 'ロングブラスターネクロ', lc: 'BLUSTER', sc: 'ロングブラスター', role: 'KILL', range: 'MID' },
    { name: 'クラッシュブラスターネオ', lc: 'BLUSTER', sc: 'クラッシュブラスター', role: 'KILL', range: 'SHORT' },
    { name: 'ラピッドブラスター', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'MID' },
    { name: 'ラピッドブラスターデコ', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'MID' },
    { name: 'ラピッドブラスターベッチュー', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'MID' },
    { name: 'ラピッドブラスターエリート', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'LONG' },
    { name: 'ラピッドブラスターエリートデコ', lc: 'BLUSTER', sc: 'ラピッドブラスター', role: 'KILL', range: 'LONG' },
    { name: 'バケットスロッシャー', lc: 'SLOSHER', sc: 'バケットスロッシャー', role: 'KILL', range: 'MID' },
    { name: 'バケットスロッシャーデコ', lc: 'SLOSHER', sc: 'バケットスロッシャー', role: 'KILL', range: 'MID' },
    { name: 'バケットスロッシャーソーダ', lc: 'SLOSHER', sc: 'バケットスロッシャー', role: 'KILL', range: 'MID' },
    { name: 'ヒッセン', lc: 'SLOSHER', sc: 'ヒッセン', role: 'BALANCED', range: 'SHORT' },
    { name: 'ヒッセンヒュー', lc: 'SLOSHER', sc: 'ヒッセン', role: 'KILL', range: 'SHORT' },
    { name: 'スクリュースロッシャー', lc: 'SLOSHER', sc: 'スクリュースロッシャー', role: 'KILL', range: 'MID' },
    { name: 'スクリュースロッシャーネオ', lc: 'SLOSHER', sc: 'スクリュースロッシャー', role: 'KILL', range: 'MID' },
    { name: 'スクリュースロッシャーベッチュー', lc: 'SLOSHER', sc: 'スクリュースロッシャー', role: 'KILL', range: 'MID' },
    { name: 'オーバーフロッシャー', lc: 'SLOSHER', sc: 'オーバーフロッシャー', role: 'BALANCED', range: 'MID' },
    { name: 'オーバーフロッシャーデコ', lc: 'SLOSHER', sc: 'オーバーフロッシャー', role: 'BALANCED', range: 'MID' },
    { name: 'エクスプロッシャー', lc: 'SLOSHER', sc: 'エクスプロッシャー', role: 'BALANCED', range: 'LONG' },
    { name: 'エクスプロッシャーカスタム', lc: 'SLOSHER', sc: 'エクスプロッシャー', role: 'BALANCED', range: 'LONG' },
    { name: 'スプラスピナー', lc: 'SPINNER', sc: 'スプラスピナー', role: 'PAINT', range: 'MID' },
    { name: 'スプラスピナーコラボ', lc: 'SPINNER', sc: 'スプラスピナー', role: 'PAINT', range: 'MID' },
    { name: 'スプラスピナーベッチュー', lc: 'SPINNER', sc: 'スプラスピナー', role: 'PAINT', range: 'MID' },
    { name: 'ノーチラス47', lc: 'SPINNER', sc: 'ノーチラス', role: 'KILL', range: 'MID' },
    { name: 'ノーチラス79', lc: 'SPINNER', sc: 'ノーチラス', role: 'KILL', range: 'MID' },
    { name: 'バレルスピナー', lc: 'SPINNER', sc: 'バレルスピナー', role: 'BALANCED', range: 'LONG' },
    { name: 'バレルスピナーデコ', lc: 'SPINNER', sc: 'バレルスピナー', role: 'BALANCED', range: 'LONG' },
    { name: 'バレルスピナーリミックス', lc: 'SPINNER', sc: 'バレルスピナー', role: 'BALANCED', range: 'LONG' },
    { name: 'クーゲルシュライバー', lc: 'SPINNER', sc: 'クーゲルシュライバー', role: 'BALANCED', range: 'LONG' },
    { name: 'クーゲルシュライバーヒュー', lc: 'SPINNER', sc: 'クーゲルシュライバー', role: 'BALANCED', range: 'LONG' },
    { name: 'ハイドラント', lc: 'SPINNER', sc: 'ハイドラント', role: 'KILL', range: 'LONG' },
    { name: 'ハイドラントカスタム', lc: 'SPINNER', sc: 'ハイドラント', role: 'KILL', range: 'LONG' },
    { name: 'スプラマニューバー', lc: 'DUALIES', sc: 'スプラマニューバー', role: 'BALANCED', range: 'SHORT' },
    { name: 'スプラマニューバーコラボ', lc: 'DUALIES', sc: 'スプラマニューバー', role: 'KILL', range: 'SHORT' },
    { name: 'スプラマニューバーベッチュー', lc: 'DUALIES', sc: 'スプラマニューバー', role: 'BALANCED', range: 'SHORT' },
    { name: 'スパッタリー', lc: 'DUALIES', sc: 'スパッタリー', role: 'BALANCED', range: 'SHORT' },
    { name: 'スパッタリーヒュー', lc: 'DUALIES', sc: 'スパッタリー', role: 'BALANCED', range: 'SHORT' },
    { name: 'スパッタリークリア', lc: 'DUALIES', sc: 'スパッタリー', role: 'BALANCED', range: 'SHORT' },
    { name: 'ケルビン525', lc: 'DUALIES', sc: 'ケルビン', role: 'KILL', range: 'MID' },
    { name: 'ケルビン525デコ', lc: 'DUALIES', sc: 'ケルビン', role: 'KILL', range: 'MID' },
    { name: 'ケルビン525ベッチュー', lc: 'DUALIES', sc: 'ケルビン', role: 'BALANCED', range: 'MID' },
    { name: 'デュアルスイーパー', lc: 'DUALIES', sc: 'デュアルスイーパー', role: 'BALANCED', range: 'MID' },
    { name: 'デュアルスイーパーカスタム', lc: 'DUALIES', sc: 'デュアルスイーパー', role: 'BALANCED', range: 'MID' },
    { name: 'クアッドホッパーブラック', lc: 'DUALIES', sc: 'クアッドホッパー', role: 'KILL', range: 'MID' },
    { name: 'クアッドホッパーホワイト', lc: 'DUALIES', sc: 'クアッドホッパー', role: 'KILL', range: 'MID' },
    { name: 'パラシェルター', lc: 'SHELTER', sc: 'パラシェルター', role: 'TANK', range: 'SHORT' },
    { name: 'パラシェルターソレーラ', lc: 'SHELTER', sc: 'パラシェルター', role: 'TANK', range: 'SHORT' },
    { name: 'キャンピングシェルター', lc: 'SHELTER', sc: 'キャンピングシェルター', role: 'TANK', range: 'MID' },
    { name: 'キャンピングシェルターソレーラ', lc: 'SHELTER', sc: 'キャンピングシェルター', role: 'TANK', range: 'MID' },
    { name: 'キャンピングシェルターカーモ', lc: 'SHELTER', sc: 'キャンピングシェルター', role: 'TANK', range: 'MID' },
    { name: 'スパイガジェット', lc: 'SHELTER', sc: 'スパイガジェット', role: 'TANK', range: 'SHORT' },
    { name: 'スパイガジェットソレーラ', lc: 'SHELTER', sc: 'スパイガジェット', role: 'TANK', range: 'SHORT' },
    { name: 'スパイガジェットベッチュー', lc: 'SHELTER', sc: 'スパイガジェット', role: 'TANK', range: 'SHORT' },
    { name: 'パブロ', lc: 'BRUSH', sc: 'パブロ', role: 'TANK', range: 'SHORT' },
    { name: 'パブロヒュー', lc: 'BRUSH', sc: 'パブロ', role: 'TANK', range: 'SHORT' },
    { name: 'パーマネントパブロ', lc: 'BRUSH', sc: 'パブロ', role: 'TANK', range: 'SHORT' },
    { name: 'ホクサイ', lc: 'BRUSH', sc: 'ホクサイ', role: 'KILL', range: 'SHORT' },
    { name: 'ホクサイヒュー', lc: 'BRUSH', sc: 'ホクサイ', role: 'KILL', range: 'SHORT' },
    { name: 'ホクサイベッチュー', lc: 'BRUSH', sc: 'ホクサイ', role: 'KILL', range: 'SHORT' },
    { name: 'スクイックリンα', lc: 'CHARGER', sc: 'スクイックリン', role: 'KILL', range: 'MID'},
    { name: 'スクイックリンβ', lc: 'CHARGER', sc: 'スクイックリン', role: 'KILL', range: 'MID'},
    { name: 'スクイックリンγ', lc: 'CHARGER', sc: 'スクイックリン', role: 'KILL', range: 'MID'},
    { name: 'ソイチューバー', lc: 'CHARGER', sc: 'ソイチューバー', role: 'BALANCED', range: 'MID'},
    { name: 'ソイチューバーカスタム', lc: 'CHARGER', sc: 'ソイチューバー', role: 'BALANCED', range: 'MID'},
    { name: '14式竹筒銃・甲', lc: 'CHARGER', sc: '14式竹筒銃', role: 'KILL', range: 'MID'},
    { name: '14式竹筒銃・乙', lc: 'CHARGER', sc: '14式竹筒銃', role: 'KILL', range: 'MID'},
    { name: '14式竹筒銃・丙', lc: 'CHARGER', sc: '14式竹筒銃', role: 'KILL', range: 'MID'},
    { name: 'スプラチャージャー', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'スプラチャージャーコラボ', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'スプラチャージャーベッチュー', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'スプラチャージャースコープ', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'スプラチャージャースコープコラボ', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'スプラチャージャースコープベッチュー', lc: 'CHARGER', sc: 'スプラチャージャー', role: 'KILL', range: 'LONG'},
    { name: 'リッター4K', lc: 'CHARGER', sc: 'リッター4K', role: 'KILL', range: 'LONG'},
    { name: 'リッター4Kカスタム', lc: 'CHARGER', sc: 'リッター4K', role: 'KILL', range: 'LONG'},
    { name: 'リッター4Kスコープ', lc: 'CHARGER', sc: 'リッター4K', role: 'KILL', range: 'LONG'},
    { name: 'リッター4Kスコープカスタム', lc: 'CHARGER', sc: 'リッター4K', role: 'KILL', range: 'LONG'},
    { name: '自由', lc: 'FREE', sc: '自由', role: 'FREE', range: 'FREE'},
] as const;